// <auto-generated />
using System;
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageContext))]
    partial class MessageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MessageBoard.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Name = "Testing 1.2.3"
                        },
                        new
                        {
                            GroupId = 2,
                            Name = "Starters"
                        },
                        new
                        {
                            GroupId = 3,
                            Name = "Builders"
                        },
                        new
                        {
                            GroupId = 4,
                            Name = "FAQ"
                        });
                });

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("MessageText")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            GroupId = 1,
                            MessageText = "Why do we have so many tests!!",
                            SentAt = new DateTime(2023, 8, 14, 11, 24, 54, 474, DateTimeKind.Local).AddTicks(9662),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 2,
                            GroupId = 2,
                            MessageText = "I've just started a wellness diet.",
                            SentAt = new DateTime(2023, 8, 14, 11, 24, 54, 474, DateTimeKind.Local).AddTicks(9717),
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 3,
                            GroupId = 3,
                            MessageText = "Hey Hey all! It's my new lego megatower!",
                            SentAt = new DateTime(2023, 8, 14, 11, 24, 54, 474, DateTimeKind.Local).AddTicks(9719),
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 4,
                            GroupId = 4,
                            MessageText = "What do I ask so I don't look dumb?",
                            SentAt = new DateTime(2023, 8, 14, 11, 24, 54, 474, DateTimeKind.Local).AddTicks(9721),
                            UserId = 4
                        },
                        new
                        {
                            MessageId = 5,
                            GroupId = 4,
                            MessageText = "Questions like What do I ask, How would I...if I were to..., To what extent does... Before asking, identify the kind of answer you're looking for, what are you assuming, is it right, and google it. Then ask.",
                            SentAt = new DateTime(2023, 8, 14, 11, 24, 54, 474, DateTimeKind.Local).AddTicks(9723),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MessageBoard.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "Adam Zapel",
                            NormalizedUserName = "bob",
                            UserName = "Bob"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Anna Conda",
                            NormalizedUserName = "long",
                            UserName = "Long"
                        },
                        new
                        {
                            UserId = 3,
                            Name = "Crystal Ball",
                            NormalizedUserName = "crall",
                            UserName = "Crall"
                        },
                        new
                        {
                            UserId = 4,
                            Name = "Dee Zaster",
                            NormalizedUserName = "deedeeha",
                            UserName = "DeeDeeHa"
                        });
                });

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.HasOne("MessageBoard.Models.Group", "Group")
                        .WithMany("Messages")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessageBoard.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessageBoard.Models.Group", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MessageBoard.Models.User", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
